package server;

public enum PayloadType {
    CONNECT, DISCONNECT, MESSAGE, CLEAR_PLAYERS, SYNC_PLAYERS, SET_COUNTDOWN, ON_START_GAME, CHOICE_GIVEN, GAME_RESULT, READY, TOTAL_READY, START_GAME, 
    OTHER_PLAYER, REMOVE_READY
}